version: '3.7'

services:
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - django_project

  django_project:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=django-insecure-cpw@$arkzokz)7m8pn2tq-eh8=m1j2slap9n&v662mm7e)mxg9
      - ALLOWED_HOSTS=localhost, 127.0.0.1, www.djngblog.tk,192.46.216.67

volumes:
  static_data: