# Generated by Django 4.0.1 on 2022-01-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_date_posted_post_date_posteded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posteded',
            new_name='date_posted',
        ),
    ]
